### PR TITLE
Drop IE11 and legacy Edge

### PR DESCRIPTION
**Pull request by mroderick**
This PR updates the `eslint` configuration to allow the use of `ES2017` syntax, which is well supported in browsers and node these days.

#### Consequences

0. Support for runtimes that don't support `ES2017` is dropped: IE11, legacy Edge, unmaintained node versions, etc.
1. New `MAJOR` version of this package
2. New  `MAJOR` version of downstream packages

#### Background

https://hackmd.io/@mroderick/sinon-rfc-drop-legacy-browsers

#### Solution

1. Rename package to be scoped to `@sinonjs`
1. Add `@studio/changes` to have a changelog
1. Import dependencies here, so downstream projects always have the correct versions 
2. Configure all rules for current `eslint`
1. Set environment to `ES2017`. This is where IE11 gets left behind.
2. Add [`eslint-plugin-mocha`](https://github.com/lo1tuma/eslint-plugin-mocha#eslint-plugin-mocha)
3. Add [`eslint-plugin-compat`](https://github.com/amilajack/eslint-plugin-compat#readme)

#### How to verify

I'm creating PRs in downstream projects that will show this in action.
This section will be updated accordingly.

### CODE REVIEW

**Comment by fatso83** [comment]
This is great stuff. Read the HackMD thing too. I don't know if I share the sentiment about config files making it harder to share/use Prettier. We have pretty standard locations and all that, so is this really a problem? I would really like to not have every line of every library be touched by this upgrade, as it makes `git blame` a bit harder to use, so if we could stick to 4 space indent that would be nice. Everything else is 👍

**Comment by mroderick** [comment]
We already adopted `prettier@2` with  https://github.com/sinonjs/sinon/pull/2324, so that ship has sailed.

Instead of using `git blame`, I recommend  using `git log -S`... that works even across renames of files.

**Comment by mroderick** [comment]
I've marked this as ready for review and will refrain from changing the commit history until we're ready to merge this

**Review by fatso83 — APPROVED** [review]

**Comment by mantoni** [comment]
There's a newer version of Studio Changes which gets the user details for the footer from the git config.

**Comment by mroderick** [comment]
> There's a newer version of Studio Changes which gets the user details for the footer from the git config.

I can push new commits containing that.

Do you have any other comments for this?

**Review by mantoni — APPROVED** [review]
Looks good 👍

**Comment by mroderick** [comment]
Could one of you try out the "How to verify" section of https://github.com/sinonjs/sinon/pull/2343 before we merge this, so we  have a good idea that this will go smoothly?

If that works well enough, then I can make draft PRs for `referee` and `referee-sinon` and we can gain some confidence in this PR.

**Pull request merged**
